# This is a basic workflow to help you get started with Actions

name: Create release branch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    # TODO: only run this on published
    types: [published, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create-release-branch:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Branch on Release
      uses: dragonchaser/github-release-watcher@master
      with:
        tag_name: ${{ github.ref }}
        release_name_prefix: Release
        github_token: ${{ secrets.GH_TOKEN }}
